// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package sqlc

import (
	generated "github.com/akiyama/inselfy/backend/internal/adapter/gateway/db/sqlc/generated"
	post "github.com/akiyama/inselfy/backend/internal/domain/post"
)

type postRowConverterImpl struct{}

func (c *postRowConverterImpl) FromGetPostWithUserByIDRow(source *generated.GetPostWithUserByIDRow) *post.PostWithUser {
	var pPostPostWithUser *post.PostWithUser
	if source != nil {
		var postPostWithUser post.PostWithUser
		postPostWithUser.Post = c.generatedGetPostWithUserByIDRowToPostPost((*source))
		postPostWithUser.Username = (*source).Username
		postPostWithUser.Name = (*source).UserName
		postPostWithUser.LikeCount = int32ToInt((*source).LikeCount)
		postPostWithUser.CommentCount = int32ToInt((*source).CommentCount)
		postPostWithUser.RepostCount = int32ToInt((*source).RepostCount)
		postPostWithUser.LikedByMe = (*source).LikedByMe
		postPostWithUser.RepostedByMe = (*source).RepostedByMe
		postPostWithUser.IsRepost = (*source).IsRepost
		pPostPostWithUser = &postPostWithUser
	}
	return pPostPostWithUser
}
func (c *postRowConverterImpl) FromListLikedPostsByUserIDRow(source *generated.ListLikedPostsByUserIDRow) *post.PostWithUser {
	var pPostPostWithUser *post.PostWithUser
	if source != nil {
		var postPostWithUser post.PostWithUser
		postPostWithUser.Post = c.generatedListLikedPostsByUserIDRowToPostPost((*source))
		postPostWithUser.Username = (*source).Username
		postPostWithUser.Name = (*source).UserName
		postPostWithUser.LikeCount = int32ToInt((*source).LikeCount)
		postPostWithUser.CommentCount = int32ToInt((*source).CommentCount)
		postPostWithUser.RepostCount = int32ToInt((*source).RepostCount)
		postPostWithUser.LikedByMe = (*source).LikedByMe
		postPostWithUser.RepostedByMe = (*source).RepostedByMe
		postPostWithUser.IsRepost = (*source).IsRepost
		pPostPostWithUser = &postPostWithUser
	}
	return pPostPostWithUser
}
func (c *postRowConverterImpl) FromListPostsByUserIDRow(source *generated.ListPostsByUserIDRow) *post.PostWithUser {
	var pPostPostWithUser *post.PostWithUser
	if source != nil {
		var postPostWithUser post.PostWithUser
		postPostWithUser.Post = c.postFromListPostsByUserIDRow((*source))
		postPostWithUser.Username = (*source).Username
		postPostWithUser.Name = (*source).UserName
		postPostWithUser.LikeCount = int32ToInt((*source).LikeCount)
		postPostWithUser.CommentCount = int32ToInt((*source).CommentCount)
		postPostWithUser.RepostCount = int32ToInt((*source).RepostCount)
		postPostWithUser.LikedByMe = (*source).LikedByMe
		postPostWithUser.RepostedByMe = (*source).RepostedByMe
		postPostWithUser.IsRepost = (*source).IsRepost
		pPostPostWithUser = &postPostWithUser
	}
	return pPostPostWithUser
}
func (c *postRowConverterImpl) FromListTimelinePostsRow(source *generated.ListTimelinePostsRow) *post.PostWithUser {
	var pPostPostWithUser *post.PostWithUser
	if source != nil {
		var postPostWithUser post.PostWithUser
		postPostWithUser.Post = c.generatedListTimelinePostsRowToPostPost((*source))
		postPostWithUser.Username = (*source).Username
		postPostWithUser.Name = (*source).UserName
		postPostWithUser.LikeCount = int32ToInt((*source).LikeCount)
		postPostWithUser.CommentCount = int32ToInt((*source).CommentCount)
		postPostWithUser.RepostCount = int32ToInt((*source).RepostCount)
		postPostWithUser.LikedByMe = (*source).LikedByMe
		postPostWithUser.RepostedByMe = (*source).RepostedByMe
		postPostWithUser.IsRepost = (*source).IsRepost
		pPostPostWithUser = &postPostWithUser
	}
	return pPostPostWithUser
}
func (c *postRowConverterImpl) generatedGetPostWithUserByIDRowToPostPost(source generated.GetPostWithUserByIDRow) post.Post {
	var postPost post.Post
	postPost.ID = uuidToString(source.ID)
	postPost.UserID = uuidToString(source.UserID)
	postPost.Content = source.Content
	postPost.QuotePostID = uuidToString(source.QuotePostID)
	postPost.CreatedAt = timestamptzToTime(source.CreatedAt)
	postPost.UpdatedAt = timestamptzToTime(source.UpdatedAt)
	return postPost
}
func (c *postRowConverterImpl) generatedListLikedPostsByUserIDRowToPostPost(source generated.ListLikedPostsByUserIDRow) post.Post {
	var postPost post.Post
	postPost.ID = uuidToString(source.ID)
	postPost.UserID = uuidToString(source.UserID)
	postPost.Content = source.Content
	postPost.QuotePostID = uuidToString(source.QuotePostID)
	postPost.CreatedAt = timestamptzToTime(source.CreatedAt)
	postPost.UpdatedAt = timestamptzToTime(source.UpdatedAt)
	return postPost
}
func (c *postRowConverterImpl) generatedListTimelinePostsRowToPostPost(source generated.ListTimelinePostsRow) post.Post {
	var postPost post.Post
	postPost.ID = uuidToString(source.ID)
	postPost.UserID = uuidToString(source.UserID)
	postPost.Content = source.Content
	postPost.QuotePostID = uuidToString(source.QuotePostID)
	postPost.CreatedAt = timestamptzToTime(source.CreatedAt)
	postPost.UpdatedAt = timestamptzToTime(source.UpdatedAt)
	return postPost
}
func (c *postRowConverterImpl) postFromListPostsByUserIDRow(source generated.ListPostsByUserIDRow) post.Post {
	var postPost post.Post
	postPost.ID = uuidToString(source.ID)
	postPost.UserID = uuidToString(source.UserID)
	postPost.Content = source.Content
	postPost.CreatedAt = timestamptzToTime(source.CreatedAt)
	postPost.UpdatedAt = timestamptzToTime(source.UpdatedAt)
	return postPost
}
