ALTER TABLE company_accounts
    ADD COLUMN IF NOT EXISTS headline TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS representative_name TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS capital TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS revenue TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS founded_month INTEGER,
    ADD COLUMN IF NOT EXISTS benefits TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS average_age TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS average_overtime_hours TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS paid_leave_rate TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS smoking_policy TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS gallery_urls JSONB NOT NULL DEFAULT '[]';
