// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package controller

import jobposting "github.com/akiyama/inselfy/backend/internal/domain/jobposting"

type jobPostingRequestConverterImpl struct{}

func (c *jobPostingRequestConverterImpl) ToCreateInput(source jobPostingRequest) jobposting.CreateJobPostingInput {
	var jobpostingCreateJobPostingInput jobposting.CreateJobPostingInput
	jobpostingCreateJobPostingInput.Title = source.Title
	jobpostingCreateJobPostingInput.Description = source.Description
	jobpostingCreateJobPostingInput.EmploymentType = source.EmploymentType
	if source.Location != nil {
		xstring := *source.Location
		jobpostingCreateJobPostingInput.Location = &xstring
	}
	jobpostingCreateJobPostingInput.Status = source.Status
	jobpostingCreateJobPostingInput.JobCategory = source.JobCategory
	jobpostingCreateJobPostingInput.HiringCount = source.HiringCount
	jobpostingCreateJobPostingInput.AppealPoints = source.AppealPoints
	jobpostingCreateJobPostingInput.Challenges = source.Challenges
	jobpostingCreateJobPostingInput.TeamDescription = source.TeamDescription
	if source.TeamMembers != nil {
		jobpostingCreateJobPostingInput.TeamMembers = make([]jobposting.TeamMember, len(source.TeamMembers))
		for i := 0; i < len(source.TeamMembers); i++ {
			jobpostingCreateJobPostingInput.TeamMembers[i] = c.jobpostingTeamMemberToJobpostingTeamMember(source.TeamMembers[i])
		}
	}
	jobpostingCreateJobPostingInput.TeamLabel = source.TeamLabel
	if source.TeamID != nil {
		xstring2 := *source.TeamID
		jobpostingCreateJobPostingInput.TeamID = &xstring2
	}
	jobpostingCreateJobPostingInput.SkillsGained = source.SkillsGained
	if source.Tags != nil {
		jobpostingCreateJobPostingInput.Tags = make([]string, len(source.Tags))
		for j := 0; j < len(source.Tags); j++ {
			jobpostingCreateJobPostingInput.Tags[j] = source.Tags[j]
		}
	}
	jobpostingCreateJobPostingInput.RequiredQualifications = source.RequiredQualifications
	jobpostingCreateJobPostingInput.PreferredQualifications = source.PreferredQualifications
	jobpostingCreateJobPostingInput.WorkLocation = source.WorkLocation
	jobpostingCreateJobPostingInput.WorkLocationChangeScope = source.WorkLocationChangeScope
	jobpostingCreateJobPostingInput.JobDescriptionChangeScope = source.JobDescriptionChangeScope
	jobpostingCreateJobPostingInput.ContractType = source.ContractType
	jobpostingCreateJobPostingInput.ProbationPeriod = source.ProbationPeriod
	jobpostingCreateJobPostingInput.WorkHours = source.WorkHours
	jobpostingCreateJobPostingInput.BreakTime = source.BreakTime
	jobpostingCreateJobPostingInput.Holidays = source.Holidays
	if source.SalaryMin != nil {
		xint32 := *source.SalaryMin
		jobpostingCreateJobPostingInput.SalaryMin = &xint32
	}
	if source.SalaryMax != nil {
		xint322 := *source.SalaryMax
		jobpostingCreateJobPostingInput.SalaryMax = &xint322
	}
	jobpostingCreateJobPostingInput.SalaryDetail = source.SalaryDetail
	jobpostingCreateJobPostingInput.Insurance = source.Insurance
	jobpostingCreateJobPostingInput.RemotePolicy = source.RemotePolicy
	jobpostingCreateJobPostingInput.Benefits = source.Benefits
	jobpostingCreateJobPostingInput.SmokingPolicy = source.SmokingPolicy
	jobpostingCreateJobPostingInput.SelectionProcess = source.SelectionProcess
	jobpostingCreateJobPostingInput.CoverImageURL = source.CoverImageURL
	jobpostingCreateJobPostingInput.HighlightTitleRole = source.HighlightTitleRole
	jobpostingCreateJobPostingInput.HighlightTitleAppeal = source.HighlightTitleAppeal
	jobpostingCreateJobPostingInput.HighlightTitleChallenge = source.HighlightTitleChallenge
	jobpostingCreateJobPostingInput.HighlightTitleGrowth = source.HighlightTitleGrowth
	if source.GalleryURLs != nil {
		jobpostingCreateJobPostingInput.GalleryURLs = make([]string, len(source.GalleryURLs))
		for k := 0; k < len(source.GalleryURLs); k++ {
			jobpostingCreateJobPostingInput.GalleryURLs[k] = source.GalleryURLs[k]
		}
	}
	return jobpostingCreateJobPostingInput
}
func (c *jobPostingRequestConverterImpl) ToUpdateInput(source jobPostingRequest) jobposting.UpdateJobPostingInput {
	var jobpostingUpdateJobPostingInput jobposting.UpdateJobPostingInput
	jobpostingUpdateJobPostingInput.Title = source.Title
	jobpostingUpdateJobPostingInput.Description = source.Description
	jobpostingUpdateJobPostingInput.EmploymentType = source.EmploymentType
	if source.Location != nil {
		xstring := *source.Location
		jobpostingUpdateJobPostingInput.Location = &xstring
	}
	jobpostingUpdateJobPostingInput.Status = source.Status
	jobpostingUpdateJobPostingInput.JobCategory = source.JobCategory
	jobpostingUpdateJobPostingInput.HiringCount = source.HiringCount
	jobpostingUpdateJobPostingInput.AppealPoints = source.AppealPoints
	jobpostingUpdateJobPostingInput.Challenges = source.Challenges
	jobpostingUpdateJobPostingInput.TeamDescription = source.TeamDescription
	if source.TeamMembers != nil {
		jobpostingUpdateJobPostingInput.TeamMembers = make([]jobposting.TeamMember, len(source.TeamMembers))
		for i := 0; i < len(source.TeamMembers); i++ {
			jobpostingUpdateJobPostingInput.TeamMembers[i] = c.jobpostingTeamMemberToJobpostingTeamMember(source.TeamMembers[i])
		}
	}
	jobpostingUpdateJobPostingInput.TeamLabel = source.TeamLabel
	if source.TeamID != nil {
		xstring2 := *source.TeamID
		jobpostingUpdateJobPostingInput.TeamID = &xstring2
	}
	jobpostingUpdateJobPostingInput.SkillsGained = source.SkillsGained
	if source.Tags != nil {
		jobpostingUpdateJobPostingInput.Tags = make([]string, len(source.Tags))
		for j := 0; j < len(source.Tags); j++ {
			jobpostingUpdateJobPostingInput.Tags[j] = source.Tags[j]
		}
	}
	jobpostingUpdateJobPostingInput.RequiredQualifications = source.RequiredQualifications
	jobpostingUpdateJobPostingInput.PreferredQualifications = source.PreferredQualifications
	jobpostingUpdateJobPostingInput.WorkLocation = source.WorkLocation
	jobpostingUpdateJobPostingInput.WorkLocationChangeScope = source.WorkLocationChangeScope
	jobpostingUpdateJobPostingInput.JobDescriptionChangeScope = source.JobDescriptionChangeScope
	jobpostingUpdateJobPostingInput.ContractType = source.ContractType
	jobpostingUpdateJobPostingInput.ProbationPeriod = source.ProbationPeriod
	jobpostingUpdateJobPostingInput.WorkHours = source.WorkHours
	jobpostingUpdateJobPostingInput.BreakTime = source.BreakTime
	jobpostingUpdateJobPostingInput.Holidays = source.Holidays
	if source.SalaryMin != nil {
		xint32 := *source.SalaryMin
		jobpostingUpdateJobPostingInput.SalaryMin = &xint32
	}
	if source.SalaryMax != nil {
		xint322 := *source.SalaryMax
		jobpostingUpdateJobPostingInput.SalaryMax = &xint322
	}
	jobpostingUpdateJobPostingInput.SalaryDetail = source.SalaryDetail
	jobpostingUpdateJobPostingInput.Insurance = source.Insurance
	jobpostingUpdateJobPostingInput.RemotePolicy = source.RemotePolicy
	jobpostingUpdateJobPostingInput.Benefits = source.Benefits
	jobpostingUpdateJobPostingInput.SmokingPolicy = source.SmokingPolicy
	jobpostingUpdateJobPostingInput.SelectionProcess = source.SelectionProcess
	jobpostingUpdateJobPostingInput.CoverImageURL = source.CoverImageURL
	jobpostingUpdateJobPostingInput.HighlightTitleRole = source.HighlightTitleRole
	jobpostingUpdateJobPostingInput.HighlightTitleAppeal = source.HighlightTitleAppeal
	jobpostingUpdateJobPostingInput.HighlightTitleChallenge = source.HighlightTitleChallenge
	jobpostingUpdateJobPostingInput.HighlightTitleGrowth = source.HighlightTitleGrowth
	if source.GalleryURLs != nil {
		jobpostingUpdateJobPostingInput.GalleryURLs = make([]string, len(source.GalleryURLs))
		for k := 0; k < len(source.GalleryURLs); k++ {
			jobpostingUpdateJobPostingInput.GalleryURLs[k] = source.GalleryURLs[k]
		}
	}
	return jobpostingUpdateJobPostingInput
}
func (c *jobPostingRequestConverterImpl) jobpostingTeamMemberToJobpostingTeamMember(source jobposting.TeamMember) jobposting.TeamMember {
	var jobpostingTeamMember jobposting.TeamMember
	jobpostingTeamMember.Name = source.Name
	jobpostingTeamMember.PhotoURL = source.PhotoURL
	return jobpostingTeamMember
}
