// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package presenter

import (
	openapi "github.com/akiyama/inselfy/backend/internal/adapter/http/generated/openapi"
	jobposting "github.com/akiyama/inselfy/backend/internal/domain/jobposting"
)

type jobPostingConverterImpl struct{}

func (c *jobPostingConverterImpl) ToResponse(source *jobposting.JobPosting) *openapi.ModelsJobPostingResponse {
	var pOpenapiModelsJobPostingResponse *openapi.ModelsJobPostingResponse
	if source != nil {
		var openapiModelsJobPostingResponse openapi.ModelsJobPostingResponse
		openapiModelsJobPostingResponse.AppealPoints = (*source).AppealPoints
		openapiModelsJobPostingResponse.Benefits = (*source).Benefits
		openapiModelsJobPostingResponse.BreakTime = (*source).BreakTime
		openapiModelsJobPostingResponse.Challenges = (*source).Challenges
		openapiModelsJobPostingResponse.CompanyId = (*source).CompanyID
		openapiModelsJobPostingResponse.CompanyLogoUrl = omitEmptyString((*source).CompanyLogoURL)
		openapiModelsJobPostingResponse.CompanyName = omitEmptyString((*source).CompanyName)
		openapiModelsJobPostingResponse.ContractType = (*source).ContractType
		openapiModelsJobPostingResponse.CoverImageUrl = (*source).CoverImageURL
		openapiModelsJobPostingResponse.CreatedAt = copyTime((*source).CreatedAt)
		openapiModelsJobPostingResponse.Description = (*source).Description
		openapiModelsJobPostingResponse.EmploymentType = (*source).EmploymentType
		openapiModelsJobPostingResponse.GalleryUrls = emptySliceIfNil((*source).GalleryURLs)
		openapiModelsJobPostingResponse.HighlightTitleAppeal = (*source).HighlightTitleAppeal
		openapiModelsJobPostingResponse.HighlightTitleChallenge = (*source).HighlightTitleChallenge
		openapiModelsJobPostingResponse.HighlightTitleGrowth = (*source).HighlightTitleGrowth
		openapiModelsJobPostingResponse.HighlightTitleRole = (*source).HighlightTitleRole
		openapiModelsJobPostingResponse.HiringCount = (*source).HiringCount
		openapiModelsJobPostingResponse.Holidays = (*source).Holidays
		openapiModelsJobPostingResponse.Id = (*source).ID
		openapiModelsJobPostingResponse.Insurance = (*source).Insurance
		openapiModelsJobPostingResponse.IsActive = (*source).IsActive
		openapiModelsJobPostingResponse.JobCategory = (*source).JobCategory
		openapiModelsJobPostingResponse.JobDescriptionChangeScope = (*source).JobDescriptionChangeScope
		if (*source).Location != nil {
			xstring := *(*source).Location
			openapiModelsJobPostingResponse.Location = &xstring
		}
		openapiModelsJobPostingResponse.PreferredQualifications = (*source).PreferredQualifications
		openapiModelsJobPostingResponse.ProbationPeriod = (*source).ProbationPeriod
		openapiModelsJobPostingResponse.RemotePolicy = (*source).RemotePolicy
		openapiModelsJobPostingResponse.RequiredQualifications = (*source).RequiredQualifications
		openapiModelsJobPostingResponse.SalaryDetail = (*source).SalaryDetail
		if (*source).SalaryMax != nil {
			xint32 := *(*source).SalaryMax
			openapiModelsJobPostingResponse.SalaryMax = &xint32
		}
		if (*source).SalaryMin != nil {
			xint322 := *(*source).SalaryMin
			openapiModelsJobPostingResponse.SalaryMin = &xint322
		}
		openapiModelsJobPostingResponse.SelectionProcess = (*source).SelectionProcess
		openapiModelsJobPostingResponse.SkillsGained = (*source).SkillsGained
		openapiModelsJobPostingResponse.SmokingPolicy = (*source).SmokingPolicy
		openapiModelsJobPostingResponse.Status = jobPostingStatusToModel((*source).Status)
		openapiModelsJobPostingResponse.Tags = emptySliceIfNil((*source).Tags)
		openapiModelsJobPostingResponse.TeamDescription = (*source).TeamDescription
		if (*source).TeamID != nil {
			xstring2 := *(*source).TeamID
			openapiModelsJobPostingResponse.TeamId = &xstring2
		}
		openapiModelsJobPostingResponse.TeamLabel = (*source).TeamLabel
		if (*source).TeamMembers != nil {
			openapiModelsJobPostingResponse.TeamMembers = make([]openapi.ModelsJobPostingTeamMember, len((*source).TeamMembers))
			for i := 0; i < len((*source).TeamMembers); i++ {
				openapiModelsJobPostingResponse.TeamMembers[i] = c.jobpostingTeamMemberToOpenapiModelsJobPostingTeamMember((*source).TeamMembers[i])
			}
		}
		openapiModelsJobPostingResponse.Title = (*source).Title
		openapiModelsJobPostingResponse.UpdatedAt = copyTime((*source).UpdatedAt)
		openapiModelsJobPostingResponse.WorkHours = (*source).WorkHours
		openapiModelsJobPostingResponse.WorkLocation = (*source).WorkLocation
		openapiModelsJobPostingResponse.WorkLocationChangeScope = (*source).WorkLocationChangeScope
		pOpenapiModelsJobPostingResponse = &openapiModelsJobPostingResponse
	}
	return pOpenapiModelsJobPostingResponse
}
func (c *jobPostingConverterImpl) ToResponses(source []*jobposting.JobPosting) []*openapi.ModelsJobPostingResponse {
	var pOpenapiModelsJobPostingResponseList []*openapi.ModelsJobPostingResponse
	if source != nil {
		pOpenapiModelsJobPostingResponseList = make([]*openapi.ModelsJobPostingResponse, len(source))
		for i := 0; i < len(source); i++ {
			pOpenapiModelsJobPostingResponseList[i] = c.ToResponse(source[i])
		}
	}
	return pOpenapiModelsJobPostingResponseList
}
func (c *jobPostingConverterImpl) jobpostingTeamMemberToOpenapiModelsJobPostingTeamMember(source jobposting.TeamMember) openapi.ModelsJobPostingTeamMember {
	var openapiModelsJobPostingTeamMember openapi.ModelsJobPostingTeamMember
	openapiModelsJobPostingTeamMember.Name = source.Name
	openapiModelsJobPostingTeamMember.PhotoUrl = omitEmptyString(source.PhotoURL)
	return openapiModelsJobPostingTeamMember
}
