// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package presenter

import jobapplication "github.com/akiyama/inselfy/backend/internal/domain/jobapplication"

type jobApplicationConverterImpl struct{}

func (c *jobApplicationConverterImpl) ToResponse(source *jobapplication.JobApplicationWithDetails) *JobApplicationResponse {
	var pPresenterJobApplicationResponse *JobApplicationResponse
	if source != nil {
		var presenterJobApplicationResponse JobApplicationResponse
		presenterJobApplicationResponse.ID = (*source).JobApplication.ID
		presenterJobApplicationResponse.JobPostingID = (*source).JobApplication.JobPostingID
		presenterJobApplicationResponse.CandidateID = (*source).JobApplication.CandidateID
		presenterJobApplicationResponse.CompanyID = (*source).JobApplication.CompanyID
		presenterJobApplicationResponse.Status = string((*source).JobApplication.Status)
		presenterJobApplicationResponse.Message = (*source).JobApplication.Message
		presenterJobApplicationResponse.JobTitle = (*source).JobTitle
		presenterJobApplicationResponse.CompanyName = (*source).CompanyName
		presenterJobApplicationResponse.CandidateName = (*source).CandidateName
		presenterJobApplicationResponse.CandidateAvatar = (*source).CandidateAvatar
		presenterJobApplicationResponse.CandidateUsername = (*source).CandidateUsername
		presenterJobApplicationResponse.CandidateHeadline = (*source).CandidateHeadline
		presenterJobApplicationResponse.CandidateProfileColor = (*source).CandidateProfileColor
		presenterJobApplicationResponse.CandidateSeekingStatus = (*source).CandidateSeekingStatus
		if (*source).CandidateSkills != nil {
			presenterJobApplicationResponse.CandidateSkills = make([]string, len((*source).CandidateSkills))
			for i := 0; i < len((*source).CandidateSkills); i++ {
				presenterJobApplicationResponse.CandidateSkills[i] = (*source).CandidateSkills[i]
			}
		}
		if (*source).WVSimilarity != nil {
			xfloat64 := *(*source).WVSimilarity
			presenterJobApplicationResponse.WVSimilarity = &xfloat64
		}
		if (*source).CISimilarity != nil {
			xfloat642 := *(*source).CISimilarity
			presenterJobApplicationResponse.CISimilarity = &xfloat642
		}
		if (*source).IntSimilarity != nil {
			xfloat643 := *(*source).IntSimilarity
			presenterJobApplicationResponse.IntSimilarity = &xfloat643
		}
		presenterJobApplicationResponse.CreatedAt = copyTime((*source).JobApplication.CreatedAt)
		presenterJobApplicationResponse.UpdatedAt = copyTime((*source).JobApplication.UpdatedAt)
		pPresenterJobApplicationResponse = &presenterJobApplicationResponse
	}
	return pPresenterJobApplicationResponse
}
func (c *jobApplicationConverterImpl) ToResponses(source []*jobapplication.JobApplicationWithDetails) []*JobApplicationResponse {
	var pPresenterJobApplicationResponseList []*JobApplicationResponse
	if source != nil {
		pPresenterJobApplicationResponseList = make([]*JobApplicationResponse, len(source))
		for i := 0; i < len(source); i++ {
			pPresenterJobApplicationResponseList[i] = c.ToResponse(source[i])
		}
	}
	return pPresenterJobApplicationResponseList
}
