// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package presenter

import (
	openapi "github.com/akiyama/inselfy/backend/internal/adapter/http/generated/openapi"
	jobapplication "github.com/akiyama/inselfy/backend/internal/domain/jobapplication"
)

type jobApplicationConverterImpl struct{}

func (c *jobApplicationConverterImpl) ToResponse(source *jobapplication.JobApplicationWithDetails) *openapi.ModelsJobApplicationResponse {
	var pOpenapiModelsJobApplicationResponse *openapi.ModelsJobApplicationResponse
	if source != nil {
		var openapiModelsJobApplicationResponse openapi.ModelsJobApplicationResponse
		openapiModelsJobApplicationResponse.CandidateAvatar = (*source).CandidateAvatar
		openapiModelsJobApplicationResponse.CandidateHeadline = (*source).CandidateHeadline
		openapiModelsJobApplicationResponse.CandidateId = (*source).JobApplication.CandidateID
		openapiModelsJobApplicationResponse.CandidateName = (*source).CandidateName
		openapiModelsJobApplicationResponse.CandidateProfileColor = omitEmptyString((*source).CandidateProfileColor)
		openapiModelsJobApplicationResponse.CandidateSeekingStatus = omitEmptyString((*source).CandidateSeekingStatus)
		openapiModelsJobApplicationResponse.CandidateSkills = omitEmptyStringSlice((*source).CandidateSkills)
		openapiModelsJobApplicationResponse.CandidateUsername = (*source).CandidateUsername
		if (*source).CISimilarity != nil {
			xfloat64 := *(*source).CISimilarity
			openapiModelsJobApplicationResponse.CiSimilarity = &xfloat64
		}
		openapiModelsJobApplicationResponse.CompanyId = (*source).JobApplication.CompanyID
		openapiModelsJobApplicationResponse.CompanyName = (*source).CompanyName
		openapiModelsJobApplicationResponse.CreatedAt = copyTime((*source).JobApplication.CreatedAt)
		openapiModelsJobApplicationResponse.Id = (*source).JobApplication.ID
		if (*source).IntSimilarity != nil {
			xfloat642 := *(*source).IntSimilarity
			openapiModelsJobApplicationResponse.IntegratedSimilarity = &xfloat642
		}
		openapiModelsJobApplicationResponse.JobPostingId = (*source).JobApplication.JobPostingID
		openapiModelsJobApplicationResponse.JobTitle = (*source).JobTitle
		openapiModelsJobApplicationResponse.Message = (*source).JobApplication.Message
		openapiModelsJobApplicationResponse.Status = jobApplicationStatusToModel((*source).JobApplication.Status)
		openapiModelsJobApplicationResponse.UpdatedAt = copyTime((*source).JobApplication.UpdatedAt)
		if (*source).WVSimilarity != nil {
			xfloat643 := *(*source).WVSimilarity
			openapiModelsJobApplicationResponse.WvSimilarity = &xfloat643
		}
		pOpenapiModelsJobApplicationResponse = &openapiModelsJobApplicationResponse
	}
	return pOpenapiModelsJobApplicationResponse
}
func (c *jobApplicationConverterImpl) ToResponses(source []*jobapplication.JobApplicationWithDetails) []*openapi.ModelsJobApplicationResponse {
	var pOpenapiModelsJobApplicationResponseList []*openapi.ModelsJobApplicationResponse
	if source != nil {
		pOpenapiModelsJobApplicationResponseList = make([]*openapi.ModelsJobApplicationResponse, len(source))
		for i := 0; i < len(source); i++ {
			pOpenapiModelsJobApplicationResponseList[i] = c.ToResponse(source[i])
		}
	}
	return pOpenapiModelsJobApplicationResponseList
}
