// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package presenter

import jobposting "github.com/akiyama/inselfy/backend/internal/domain/jobposting"

type jobPostingConverterImpl struct{}

func (c *jobPostingConverterImpl) ToResponse(source *jobposting.JobPosting) *jobPostingResponse {
	var pPresenterjobPostingResponse *jobPostingResponse
	if source != nil {
		var presenterjobPostingResponse jobPostingResponse
		presenterjobPostingResponse.ID = (*source).ID
		presenterjobPostingResponse.CompanyID = (*source).CompanyID
		presenterjobPostingResponse.CompanyName = (*source).CompanyName
		presenterjobPostingResponse.CompanyLogoURL = (*source).CompanyLogoURL
		presenterjobPostingResponse.Title = (*source).Title
		presenterjobPostingResponse.Description = (*source).Description
		presenterjobPostingResponse.EmploymentType = (*source).EmploymentType
		if (*source).Location != nil {
			xstring := *(*source).Location
			presenterjobPostingResponse.Location = &xstring
		}
		presenterjobPostingResponse.IsActive = (*source).IsActive
		presenterjobPostingResponse.Status = (*source).Status
		presenterjobPostingResponse.JobCategory = (*source).JobCategory
		presenterjobPostingResponse.HiringCount = (*source).HiringCount
		presenterjobPostingResponse.AppealPoints = (*source).AppealPoints
		presenterjobPostingResponse.Challenges = (*source).Challenges
		presenterjobPostingResponse.TeamDescription = (*source).TeamDescription
		if (*source).TeamMembers != nil {
			presenterjobPostingResponse.TeamMembers = make([]jobposting.TeamMember, len((*source).TeamMembers))
			for i := 0; i < len((*source).TeamMembers); i++ {
				presenterjobPostingResponse.TeamMembers[i] = c.jobpostingTeamMemberToJobpostingTeamMember((*source).TeamMembers[i])
			}
		}
		presenterjobPostingResponse.TeamLabel = (*source).TeamLabel
		if (*source).TeamID != nil {
			xstring2 := *(*source).TeamID
			presenterjobPostingResponse.TeamID = &xstring2
		}
		presenterjobPostingResponse.SkillsGained = (*source).SkillsGained
		presenterjobPostingResponse.Tags = emptySliceIfNil((*source).Tags)
		presenterjobPostingResponse.RequiredQualifications = (*source).RequiredQualifications
		presenterjobPostingResponse.PreferredQualifications = (*source).PreferredQualifications
		presenterjobPostingResponse.WorkLocation = (*source).WorkLocation
		presenterjobPostingResponse.WorkLocationChangeScope = (*source).WorkLocationChangeScope
		presenterjobPostingResponse.JobDescriptionChangeScope = (*source).JobDescriptionChangeScope
		presenterjobPostingResponse.ContractType = (*source).ContractType
		presenterjobPostingResponse.ProbationPeriod = (*source).ProbationPeriod
		presenterjobPostingResponse.WorkHours = (*source).WorkHours
		presenterjobPostingResponse.BreakTime = (*source).BreakTime
		presenterjobPostingResponse.Holidays = (*source).Holidays
		if (*source).SalaryMin != nil {
			xint32 := *(*source).SalaryMin
			presenterjobPostingResponse.SalaryMin = &xint32
		}
		if (*source).SalaryMax != nil {
			xint322 := *(*source).SalaryMax
			presenterjobPostingResponse.SalaryMax = &xint322
		}
		presenterjobPostingResponse.SalaryDetail = (*source).SalaryDetail
		presenterjobPostingResponse.Insurance = (*source).Insurance
		presenterjobPostingResponse.RemotePolicy = (*source).RemotePolicy
		presenterjobPostingResponse.Benefits = (*source).Benefits
		presenterjobPostingResponse.SmokingPolicy = (*source).SmokingPolicy
		presenterjobPostingResponse.SelectionProcess = (*source).SelectionProcess
		presenterjobPostingResponse.CoverImageURL = (*source).CoverImageURL
		presenterjobPostingResponse.HighlightTitleRole = (*source).HighlightTitleRole
		presenterjobPostingResponse.HighlightTitleAppeal = (*source).HighlightTitleAppeal
		presenterjobPostingResponse.HighlightTitleChallenge = (*source).HighlightTitleChallenge
		presenterjobPostingResponse.HighlightTitleGrowth = (*source).HighlightTitleGrowth
		presenterjobPostingResponse.GalleryURLs = emptySliceIfNil((*source).GalleryURLs)
		presenterjobPostingResponse.CreatedAt = copyTime((*source).CreatedAt)
		presenterjobPostingResponse.UpdatedAt = copyTime((*source).UpdatedAt)
		pPresenterjobPostingResponse = &presenterjobPostingResponse
	}
	return pPresenterjobPostingResponse
}
func (c *jobPostingConverterImpl) ToResponses(source []*jobposting.JobPosting) []*jobPostingResponse {
	var pPresenterjobPostingResponseList []*jobPostingResponse
	if source != nil {
		pPresenterjobPostingResponseList = make([]*jobPostingResponse, len(source))
		for i := 0; i < len(source); i++ {
			pPresenterjobPostingResponseList[i] = c.ToResponse(source[i])
		}
	}
	return pPresenterjobPostingResponseList
}
func (c *jobPostingConverterImpl) jobpostingTeamMemberToJobpostingTeamMember(source jobposting.TeamMember) jobposting.TeamMember {
	var jobpostingTeamMember jobposting.TeamMember
	jobpostingTeamMember.Name = source.Name
	jobpostingTeamMember.PhotoURL = source.PhotoURL
	return jobpostingTeamMember
}
