// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package presenter

import (
	openapi "github.com/akiyama/inselfy/backend/internal/adapter/http/generated/openapi"
	messaging "github.com/akiyama/inselfy/backend/internal/domain/messaging"
)

type messagingConverterImpl struct{}

func (c *messagingConverterImpl) ToConversationResponse(source *messaging.ConversationWithPreview) *openapi.ModelsConversationResponse {
	var pOpenapiModelsConversationResponse *openapi.ModelsConversationResponse
	if source != nil {
		var openapiModelsConversationResponse openapi.ModelsConversationResponse
		openapiModelsConversationResponse.CandidateId = (*source).Conversation.CandidateID
		openapiModelsConversationResponse.CandidateName = (*source).CandidateName
		openapiModelsConversationResponse.CompanyId = (*source).Conversation.CompanyID
		openapiModelsConversationResponse.CompanyName = (*source).CompanyName
		openapiModelsConversationResponse.ConversationType = (*source).Conversation.ConversationType
		openapiModelsConversationResponse.CreatedAt = copyTime((*source).Conversation.CreatedAt)
		openapiModelsConversationResponse.Id = (*source).Conversation.ID
		openapiModelsConversationResponse.LastMessageAt = copyTime((*source).Conversation.LastMessageAt)
		if (*source).LastMessageBody != nil {
			xstring := *(*source).LastMessageBody
			openapiModelsConversationResponse.LastMessageBody = &xstring
		}
		openapiModelsConversationResponse.Participant1Id = omitEmptyString((*source).Conversation.Participant1ID)
		openapiModelsConversationResponse.Participant1Name = omitEmptyString((*source).Participant1Name)
		openapiModelsConversationResponse.Participant2Id = omitEmptyString((*source).Conversation.Participant2ID)
		openapiModelsConversationResponse.Participant2Name = omitEmptyString((*source).Participant2Name)
		openapiModelsConversationResponse.UnreadCount = (*source).UnreadCount
		pOpenapiModelsConversationResponse = &openapiModelsConversationResponse
	}
	return pOpenapiModelsConversationResponse
}
func (c *messagingConverterImpl) ToConversationResponses(source []*messaging.ConversationWithPreview) []*openapi.ModelsConversationResponse {
	var pOpenapiModelsConversationResponseList []*openapi.ModelsConversationResponse
	if source != nil {
		pOpenapiModelsConversationResponseList = make([]*openapi.ModelsConversationResponse, len(source))
		for i := 0; i < len(source); i++ {
			pOpenapiModelsConversationResponseList[i] = c.ToConversationResponse(source[i])
		}
	}
	return pOpenapiModelsConversationResponseList
}
