// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package presenter

import messaging "github.com/akiyama/inselfy/backend/internal/domain/messaging"

type messagingConverterImpl struct{}

func (c *messagingConverterImpl) ToConversationResponse(source *messaging.ConversationWithPreview) *conversationResponse {
	var pPresenterconversationResponse *conversationResponse
	if source != nil {
		var presenterconversationResponse conversationResponse
		presenterconversationResponse.ID = (*source).Conversation.ID
		presenterconversationResponse.ConversationType = (*source).Conversation.ConversationType
		presenterconversationResponse.CompanyID = (*source).Conversation.CompanyID
		presenterconversationResponse.CandidateID = (*source).Conversation.CandidateID
		presenterconversationResponse.CompanyName = (*source).CompanyName
		presenterconversationResponse.CandidateName = (*source).CandidateName
		presenterconversationResponse.Participant1ID = (*source).Conversation.Participant1ID
		presenterconversationResponse.Participant2ID = (*source).Conversation.Participant2ID
		presenterconversationResponse.Participant1Name = (*source).Participant1Name
		presenterconversationResponse.Participant2Name = (*source).Participant2Name
		if (*source).LastMessageBody != nil {
			xstring := *(*source).LastMessageBody
			presenterconversationResponse.LastMessageBody = &xstring
		}
		presenterconversationResponse.LastMessageAt = copyTime((*source).Conversation.LastMessageAt)
		presenterconversationResponse.UnreadCount = (*source).UnreadCount
		presenterconversationResponse.CreatedAt = copyTime((*source).Conversation.CreatedAt)
		pPresenterconversationResponse = &presenterconversationResponse
	}
	return pPresenterconversationResponse
}
func (c *messagingConverterImpl) ToConversationResponses(source []*messaging.ConversationWithPreview) []*conversationResponse {
	var pPresenterconversationResponseList []*conversationResponse
	if source != nil {
		pPresenterconversationResponseList = make([]*conversationResponse, len(source))
		for i := 0; i < len(source); i++ {
			pPresenterconversationResponseList[i] = c.ToConversationResponse(source[i])
		}
	}
	return pPresenterconversationResponseList
}
