// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package presenter

import post "github.com/akiyama/inselfy/backend/internal/domain/post"

type postConverterImpl struct{}

func (c *postConverterImpl) ToCommentResponse(source *post.CommentWithUser) *CommentResponse {
	var pPresenterCommentResponse *CommentResponse
	if source != nil {
		var presenterCommentResponse CommentResponse
		presenterCommentResponse.ID = (*source).Comment.ID
		presenterCommentResponse.PostID = (*source).Comment.PostID
		presenterCommentResponse.UserID = (*source).Comment.UserID
		presenterCommentResponse.Username = (*source).Username
		presenterCommentResponse.Name = (*source).Name
		presenterCommentResponse.Content = (*source).Comment.Content
		presenterCommentResponse.CreatedAt = copyTime((*source).Comment.CreatedAt)
		pPresenterCommentResponse = &presenterCommentResponse
	}
	return pPresenterCommentResponse
}
func (c *postConverterImpl) ToPostResponse(source *post.PostWithUser) *PostResponse {
	var pPresenterPostResponse *PostResponse
	if source != nil {
		var presenterPostResponse PostResponse
		presenterPostResponse.ID = (*source).Post.ID
		presenterPostResponse.UserID = (*source).Post.UserID
		presenterPostResponse.Username = (*source).Username
		presenterPostResponse.Name = (*source).Name
		presenterPostResponse.Content = (*source).Post.Content
		presenterPostResponse.LikeCount = (*source).LikeCount
		presenterPostResponse.CommentCount = (*source).CommentCount
		presenterPostResponse.RepostCount = (*source).RepostCount
		presenterPostResponse.LikedByMe = (*source).LikedByMe
		presenterPostResponse.RepostedByMe = (*source).RepostedByMe
		presenterPostResponse.IsRepost = (*source).IsRepost
		presenterPostResponse.QuotedPost = c.pPostQuotedPostToPPresenterQuotedPostResponse((*source).QuotedPost)
		presenterPostResponse.CreatedAt = copyTime((*source).Post.CreatedAt)
		presenterPostResponse.UpdatedAt = copyTime((*source).Post.UpdatedAt)
		pPresenterPostResponse = &presenterPostResponse
	}
	return pPresenterPostResponse
}
func (c *postConverterImpl) pPostQuotedPostToPPresenterQuotedPostResponse(source *post.QuotedPost) *QuotedPostResponse {
	var pPresenterQuotedPostResponse *QuotedPostResponse
	if source != nil {
		var presenterQuotedPostResponse QuotedPostResponse
		presenterQuotedPostResponse.ID = (*source).ID
		presenterQuotedPostResponse.Content = (*source).Content
		presenterQuotedPostResponse.Username = (*source).Username
		presenterQuotedPostResponse.Name = (*source).Name
		presenterQuotedPostResponse.CreatedAt = copyTime((*source).CreatedAt)
		pPresenterQuotedPostResponse = &presenterQuotedPostResponse
	}
	return pPresenterQuotedPostResponse
}
