// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package presenter

import (
	openapi "github.com/akiyama/inselfy/backend/internal/adapter/http/generated/openapi"
	post "github.com/akiyama/inselfy/backend/internal/domain/post"
)

type postConverterImpl struct{}

func (c *postConverterImpl) ToCommentResponse(source *post.CommentWithUser) *openapi.ModelsCommentResponse {
	var pOpenapiModelsCommentResponse *openapi.ModelsCommentResponse
	if source != nil {
		var openapiModelsCommentResponse openapi.ModelsCommentResponse
		openapiModelsCommentResponse.Content = (*source).Comment.Content
		openapiModelsCommentResponse.CreatedAt = copyTime((*source).Comment.CreatedAt)
		openapiModelsCommentResponse.Id = (*source).Comment.ID
		openapiModelsCommentResponse.Name = (*source).Name
		openapiModelsCommentResponse.PostId = (*source).Comment.PostID
		openapiModelsCommentResponse.UserId = (*source).Comment.UserID
		openapiModelsCommentResponse.Username = (*source).Username
		pOpenapiModelsCommentResponse = &openapiModelsCommentResponse
	}
	return pOpenapiModelsCommentResponse
}
func (c *postConverterImpl) ToPostResponse(source *post.PostWithUser) *openapi.ModelsPostResponse {
	var pOpenapiModelsPostResponse *openapi.ModelsPostResponse
	if source != nil {
		var openapiModelsPostResponse openapi.ModelsPostResponse
		openapiModelsPostResponse.CommentCount = (*source).CommentCount
		openapiModelsPostResponse.Content = (*source).Post.Content
		openapiModelsPostResponse.CreatedAt = copyTime((*source).Post.CreatedAt)
		openapiModelsPostResponse.Id = (*source).Post.ID
		openapiModelsPostResponse.IsRepost = (*source).IsRepost
		openapiModelsPostResponse.LikeCount = (*source).LikeCount
		openapiModelsPostResponse.LikedByMe = (*source).LikedByMe
		openapiModelsPostResponse.Name = (*source).Name
		openapiModelsPostResponse.QuotedPost = c.pPostQuotedPostToPOpenapiModelsQuotedPostResponse((*source).QuotedPost)
		openapiModelsPostResponse.RepostCount = (*source).RepostCount
		openapiModelsPostResponse.RepostedByMe = (*source).RepostedByMe
		openapiModelsPostResponse.UpdatedAt = copyTime((*source).Post.UpdatedAt)
		openapiModelsPostResponse.UserId = (*source).Post.UserID
		openapiModelsPostResponse.Username = (*source).Username
		pOpenapiModelsPostResponse = &openapiModelsPostResponse
	}
	return pOpenapiModelsPostResponse
}
func (c *postConverterImpl) pPostQuotedPostToPOpenapiModelsQuotedPostResponse(source *post.QuotedPost) *openapi.ModelsQuotedPostResponse {
	var pOpenapiModelsQuotedPostResponse *openapi.ModelsQuotedPostResponse
	if source != nil {
		var openapiModelsQuotedPostResponse openapi.ModelsQuotedPostResponse
		openapiModelsQuotedPostResponse.Content = (*source).Content
		openapiModelsQuotedPostResponse.CreatedAt = copyTime((*source).CreatedAt)
		openapiModelsQuotedPostResponse.Id = (*source).ID
		openapiModelsQuotedPostResponse.Name = (*source).Name
		openapiModelsQuotedPostResponse.Username = (*source).Username
		pOpenapiModelsQuotedPostResponse = &openapiModelsQuotedPostResponse
	}
	return pOpenapiModelsQuotedPostResponse
}
