// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package presenter

import (
	openapi "github.com/akiyama/inselfy/backend/internal/adapter/http/generated/openapi"
	scout "github.com/akiyama/inselfy/backend/internal/domain/scout"
	"time"
)

type scoutConverterImpl struct{}

func (c *scoutConverterImpl) ToScoutMessageResponse(source *scout.ScoutMessageWithNames) *openapi.ModelsScoutMessageResponse {
	var pOpenapiModelsScoutMessageResponse *openapi.ModelsScoutMessageResponse
	if source != nil {
		var openapiModelsScoutMessageResponse openapi.ModelsScoutMessageResponse
		openapiModelsScoutMessageResponse.Body = (*source).ScoutMessage.Body
		openapiModelsScoutMessageResponse.CandidateId = (*source).ScoutMessage.CandidateID
		openapiModelsScoutMessageResponse.CandidateName = (*source).CandidateName
		openapiModelsScoutMessageResponse.CompanyId = (*source).ScoutMessage.CompanyID
		openapiModelsScoutMessageResponse.CompanyName = (*source).CompanyName
		openapiModelsScoutMessageResponse.CreatedAt = copyTime((*source).ScoutMessage.CreatedAt)
		openapiModelsScoutMessageResponse.ExpiresAt = c.pTimeTimeToPTimeTime((*source).ScoutMessage.ExpiresAt)
		openapiModelsScoutMessageResponse.Id = (*source).ScoutMessage.ID
		if (*source).ScoutMessage.JobPostingID != nil {
			xstring := *(*source).ScoutMessage.JobPostingID
			openapiModelsScoutMessageResponse.JobPostingId = &xstring
		}
		if (*source).JobTitle != nil {
			xstring2 := *(*source).JobTitle
			openapiModelsScoutMessageResponse.JobTitle = &xstring2
		}
		openapiModelsScoutMessageResponse.OpenedAt = c.pTimeTimeToPTimeTime((*source).ScoutMessage.OpenedAt)
		openapiModelsScoutMessageResponse.RepliedAt = c.pTimeTimeToPTimeTime((*source).ScoutMessage.RepliedAt)
		openapiModelsScoutMessageResponse.SentAt = c.pTimeTimeToPTimeTime((*source).ScoutMessage.SentAt)
		openapiModelsScoutMessageResponse.Status = scoutStatusToString((*source).ScoutMessage.Status)
		openapiModelsScoutMessageResponse.Subject = (*source).ScoutMessage.Subject
		pOpenapiModelsScoutMessageResponse = &openapiModelsScoutMessageResponse
	}
	return pOpenapiModelsScoutMessageResponse
}
func (c *scoutConverterImpl) ToScoutReplyResponses(source []*scout.ScoutReply) []openapi.ModelsScoutReplyResponse {
	var openapiModelsScoutReplyResponseList []openapi.ModelsScoutReplyResponse
	if source != nil {
		openapiModelsScoutReplyResponseList = make([]openapi.ModelsScoutReplyResponse, len(source))
		for i := 0; i < len(source); i++ {
			openapiModelsScoutReplyResponseList[i] = c.pScoutScoutReplyToOpenapiModelsScoutReplyResponse(source[i])
		}
	}
	return openapiModelsScoutReplyResponseList
}
func (c *scoutConverterImpl) pScoutScoutReplyToOpenapiModelsScoutReplyResponse(source *scout.ScoutReply) openapi.ModelsScoutReplyResponse {
	var openapiModelsScoutReplyResponse openapi.ModelsScoutReplyResponse
	if source != nil {
		openapiModelsScoutReplyResponse.Body = (*source).Body
		openapiModelsScoutReplyResponse.CreatedAt = copyTime((*source).CreatedAt)
		openapiModelsScoutReplyResponse.Id = (*source).ID
		openapiModelsScoutReplyResponse.SenderId = (*source).SenderID
		openapiModelsScoutReplyResponse.SenderType = (*source).SenderType
	}
	return openapiModelsScoutReplyResponse
}
func (c *scoutConverterImpl) pTimeTimeToPTimeTime(source *time.Time) *time.Time {
	var pTimeTime *time.Time
	if source != nil {
		timeTime := copyTime((*source))
		pTimeTime = &timeTime
	}
	return pTimeTime
}
