// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package presenter

import (
	scout "github.com/akiyama/inselfy/backend/internal/domain/scout"
	"time"
)

type scoutConverterImpl struct{}

func (c *scoutConverterImpl) ToScoutMessageResponse(source *scout.ScoutMessageWithNames) *scoutMessageResponse {
	var pPresenterscoutMessageResponse *scoutMessageResponse
	if source != nil {
		var presenterscoutMessageResponse scoutMessageResponse
		presenterscoutMessageResponse.ID = (*source).ScoutMessage.ID
		presenterscoutMessageResponse.CompanyID = (*source).ScoutMessage.CompanyID
		presenterscoutMessageResponse.CandidateID = (*source).ScoutMessage.CandidateID
		if (*source).ScoutMessage.JobPostingID != nil {
			xstring := *(*source).ScoutMessage.JobPostingID
			presenterscoutMessageResponse.JobPostingID = &xstring
		}
		presenterscoutMessageResponse.Subject = (*source).ScoutMessage.Subject
		presenterscoutMessageResponse.Body = (*source).ScoutMessage.Body
		presenterscoutMessageResponse.Status = scoutStatusToString((*source).ScoutMessage.Status)
		presenterscoutMessageResponse.CompanyName = (*source).CompanyName
		presenterscoutMessageResponse.CandidateName = (*source).CandidateName
		if (*source).JobTitle != nil {
			xstring2 := *(*source).JobTitle
			presenterscoutMessageResponse.JobTitle = &xstring2
		}
		presenterscoutMessageResponse.SentAt = c.pTimeTimeToPTimeTime((*source).ScoutMessage.SentAt)
		presenterscoutMessageResponse.OpenedAt = c.pTimeTimeToPTimeTime((*source).ScoutMessage.OpenedAt)
		presenterscoutMessageResponse.RepliedAt = c.pTimeTimeToPTimeTime((*source).ScoutMessage.RepliedAt)
		presenterscoutMessageResponse.ExpiresAt = c.pTimeTimeToPTimeTime((*source).ScoutMessage.ExpiresAt)
		presenterscoutMessageResponse.CreatedAt = copyTime((*source).ScoutMessage.CreatedAt)
		pPresenterscoutMessageResponse = &presenterscoutMessageResponse
	}
	return pPresenterscoutMessageResponse
}
func (c *scoutConverterImpl) ToScoutReplyResponses(source []*scout.ScoutReply) []*scoutReplyResponse {
	var pPresenterscoutReplyResponseList []*scoutReplyResponse
	if source != nil {
		pPresenterscoutReplyResponseList = make([]*scoutReplyResponse, len(source))
		for i := 0; i < len(source); i++ {
			pPresenterscoutReplyResponseList[i] = c.pScoutScoutReplyToPPresenterscoutReplyResponse(source[i])
		}
	}
	return pPresenterscoutReplyResponseList
}
func (c *scoutConverterImpl) pScoutScoutReplyToPPresenterscoutReplyResponse(source *scout.ScoutReply) *scoutReplyResponse {
	var pPresenterscoutReplyResponse *scoutReplyResponse
	if source != nil {
		var presenterscoutReplyResponse scoutReplyResponse
		presenterscoutReplyResponse.ID = (*source).ID
		presenterscoutReplyResponse.SenderType = (*source).SenderType
		presenterscoutReplyResponse.SenderID = (*source).SenderID
		presenterscoutReplyResponse.Body = (*source).Body
		presenterscoutReplyResponse.CreatedAt = copyTime((*source).CreatedAt)
		pPresenterscoutReplyResponse = &presenterscoutReplyResponse
	}
	return pPresenterscoutReplyResponse
}
func (c *scoutConverterImpl) pTimeTimeToPTimeTime(source *time.Time) *time.Time {
	var pTimeTime *time.Time
	if source != nil {
		timeTime := copyTime((*source))
		pTimeTime = &timeTime
	}
	return pTimeTime
}
