// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package usecase

import jobposting "github.com/akiyama/inselfy/backend/internal/domain/jobposting"

type jobPostingEntityConverterImpl struct{}

func (c *jobPostingEntityConverterImpl) CreateInputToEntity(source jobposting.CreateJobPostingInput) *jobposting.JobPosting {
	var jobpostingJobPosting jobposting.JobPosting
	jobpostingJobPosting.CompanyID = source.CompanyID
	jobpostingJobPosting.Title = source.Title
	jobpostingJobPosting.Description = source.Description
	jobpostingJobPosting.EmploymentType = source.EmploymentType
	if source.Location != nil {
		xstring := *source.Location
		jobpostingJobPosting.Location = &xstring
	}
	jobpostingJobPosting.JobCategory = source.JobCategory
	jobpostingJobPosting.HiringCount = source.HiringCount
	jobpostingJobPosting.AppealPoints = source.AppealPoints
	jobpostingJobPosting.Challenges = source.Challenges
	jobpostingJobPosting.TeamDescription = source.TeamDescription
	if source.TeamMembers != nil {
		jobpostingJobPosting.TeamMembers = make([]jobposting.TeamMember, len(source.TeamMembers))
		for i := 0; i < len(source.TeamMembers); i++ {
			jobpostingJobPosting.TeamMembers[i] = c.jobpostingTeamMemberToJobpostingTeamMember(source.TeamMembers[i])
		}
	}
	jobpostingJobPosting.TeamLabel = source.TeamLabel
	if source.TeamID != nil {
		xstring2 := *source.TeamID
		jobpostingJobPosting.TeamID = &xstring2
	}
	jobpostingJobPosting.SkillsGained = source.SkillsGained
	if source.Tags != nil {
		jobpostingJobPosting.Tags = make([]string, len(source.Tags))
		for j := 0; j < len(source.Tags); j++ {
			jobpostingJobPosting.Tags[j] = source.Tags[j]
		}
	}
	jobpostingJobPosting.RequiredQualifications = source.RequiredQualifications
	jobpostingJobPosting.PreferredQualifications = source.PreferredQualifications
	jobpostingJobPosting.WorkLocation = source.WorkLocation
	jobpostingJobPosting.WorkLocationChangeScope = source.WorkLocationChangeScope
	jobpostingJobPosting.JobDescriptionChangeScope = source.JobDescriptionChangeScope
	jobpostingJobPosting.ContractType = source.ContractType
	jobpostingJobPosting.ProbationPeriod = source.ProbationPeriod
	jobpostingJobPosting.WorkHours = source.WorkHours
	jobpostingJobPosting.BreakTime = source.BreakTime
	jobpostingJobPosting.Holidays = source.Holidays
	if source.SalaryMin != nil {
		xint32 := *source.SalaryMin
		jobpostingJobPosting.SalaryMin = &xint32
	}
	if source.SalaryMax != nil {
		xint322 := *source.SalaryMax
		jobpostingJobPosting.SalaryMax = &xint322
	}
	jobpostingJobPosting.SalaryDetail = source.SalaryDetail
	jobpostingJobPosting.Insurance = source.Insurance
	jobpostingJobPosting.RemotePolicy = source.RemotePolicy
	jobpostingJobPosting.Benefits = source.Benefits
	jobpostingJobPosting.SmokingPolicy = source.SmokingPolicy
	jobpostingJobPosting.SelectionProcess = source.SelectionProcess
	jobpostingJobPosting.CoverImageURL = source.CoverImageURL
	jobpostingJobPosting.HighlightTitleRole = source.HighlightTitleRole
	jobpostingJobPosting.HighlightTitleAppeal = source.HighlightTitleAppeal
	jobpostingJobPosting.HighlightTitleChallenge = source.HighlightTitleChallenge
	jobpostingJobPosting.HighlightTitleGrowth = source.HighlightTitleGrowth
	if source.GalleryURLs != nil {
		jobpostingJobPosting.GalleryURLs = make([]string, len(source.GalleryURLs))
		for k := 0; k < len(source.GalleryURLs); k++ {
			jobpostingJobPosting.GalleryURLs[k] = source.GalleryURLs[k]
		}
	}
	return &jobpostingJobPosting
}
func (c *jobPostingEntityConverterImpl) jobpostingTeamMemberToJobpostingTeamMember(source jobposting.TeamMember) jobposting.TeamMember {
	var jobpostingTeamMember jobposting.TeamMember
	jobpostingTeamMember.Name = source.Name
	jobpostingTeamMember.PhotoURL = source.PhotoURL
	return jobpostingTeamMember
}
